# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: c:/Users/zfsalti/488/MP-2/MP2.xpr/MP2/MP2.srcs/sources_1/bd/system/ip/system_v_proc_ss_1_0/bd_0/ip/ip_0/bd_ed01_hcr_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_ed01_hcr_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/zfsalti/488/MP-2/MP2.xpr/MP2/MP2.srcs/sources_1/bd/system/ip/system_v_proc_ss_1_0/bd_0/ip/ip_0/bd_ed01_hcr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_ed01_hcr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/zfsalti/488/MP-2/MP2.xpr/MP2/MP2.srcs/sources_1/bd/system/ip/system_v_proc_ss_1_0/bd_0/ip/ip_0/bd_ed01_hcr_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_ed01_hcr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/zfsalti/488/MP-2/MP2.xpr/MP2/MP2.srcs/sources_1/bd/system/ip/system_v_proc_ss_1_0/bd_0/ip/ip_0/bd_ed01_hcr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_ed01_hcr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
