# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/zfsalti/488/MP-2/MP2.xpr/MP2/MP2.srcs/sources_1/bd/system/ip/system_v_proc_ss_1_0/system_v_proc_ss_1_0.xci
# IP: The module: 'system_v_proc_ss_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/zfsalti/488/MP-2/MP2.xpr/MP2/MP2.srcs/sources_1/bd/system/ip/system_v_proc_ss_1_0/bd_0/bd_ed01.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_ed01 || ORIG_REF_NAME==bd_ed01} -quiet] -quiet

# IP: c:/Users/zfsalti/488/MP-2/MP2.xpr/MP2/MP2.srcs/sources_1/bd/system/ip/system_v_proc_ss_1_0/bd_0/ip/ip_0/bd_ed01_hcr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_ed01_hcr_0 || ORIG_REF_NAME==bd_ed01_hcr_0} -quiet] -quiet

# XDC: c:/Users/zfsalti/488/MP-2/MP2.xpr/MP2/MP2.srcs/sources_1/bd/system/ip/system_v_proc_ss_1_0/bd_0/bd_ed01_ooc.xdc

# XDC: c:/Users/zfsalti/488/MP-2/MP2.xpr/MP2/MP2.srcs/sources_1/bd/system/ip/system_v_proc_ss_1_0/system_v_proc_ss_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_v_proc_ss_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/zfsalti/488/MP-2/MP2.xpr/MP2/MP2.srcs/sources_1/bd/system/ip/system_v_proc_ss_1_0/system_v_proc_ss_1_0.xci
# IP: The module: 'system_v_proc_ss_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/zfsalti/488/MP-2/MP2.xpr/MP2/MP2.srcs/sources_1/bd/system/ip/system_v_proc_ss_1_0/bd_0/bd_ed01.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_ed01 || ORIG_REF_NAME==bd_ed01} -quiet] -quiet

# IP: c:/Users/zfsalti/488/MP-2/MP2.xpr/MP2/MP2.srcs/sources_1/bd/system/ip/system_v_proc_ss_1_0/bd_0/ip/ip_0/bd_ed01_hcr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_ed01_hcr_0 || ORIG_REF_NAME==bd_ed01_hcr_0} -quiet] -quiet

# XDC: c:/Users/zfsalti/488/MP-2/MP2.xpr/MP2/MP2.srcs/sources_1/bd/system/ip/system_v_proc_ss_1_0/bd_0/bd_ed01_ooc.xdc

# XDC: c:/Users/zfsalti/488/MP-2/MP2.xpr/MP2/MP2.srcs/sources_1/bd/system/ip/system_v_proc_ss_1_0/system_v_proc_ss_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_v_proc_ss_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
