# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/zfsalti/488/MP-2/MP2.xpr/MP2/MP2.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/system_v_proc_ss_0_0.xci
# IP: The module: 'system_v_proc_ss_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/zfsalti/488/MP-2/MP2.xpr/MP2/MP2.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/bd_2d50.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2d50 || ORIG_REF_NAME==bd_2d50} -quiet] -quiet

# IP: c:/Users/zfsalti/488/MP-2/MP2.xpr/MP2/MP2.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_0/bd_2d50_csc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2d50_csc_0 || ORIG_REF_NAME==bd_2d50_csc_0} -quiet] -quiet

# XDC: c:/Users/zfsalti/488/MP-2/MP2.xpr/MP2/MP2.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/bd_2d50_ooc.xdc

# XDC: c:/Users/zfsalti/488/MP-2/MP2.xpr/MP2/MP2.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/system_v_proc_ss_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_v_proc_ss_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/zfsalti/488/MP-2/MP2.xpr/MP2/MP2.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/system_v_proc_ss_0_0.xci
# IP: The module: 'system_v_proc_ss_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/zfsalti/488/MP-2/MP2.xpr/MP2/MP2.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/bd_2d50.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2d50 || ORIG_REF_NAME==bd_2d50} -quiet] -quiet

# IP: c:/Users/zfsalti/488/MP-2/MP2.xpr/MP2/MP2.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_0/bd_2d50_csc_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2d50_csc_0 || ORIG_REF_NAME==bd_2d50_csc_0} -quiet] -quiet

# XDC: c:/Users/zfsalti/488/MP-2/MP2.xpr/MP2/MP2.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/bd_2d50_ooc.xdc

# XDC: c:/Users/zfsalti/488/MP-2/MP2.xpr/MP2/MP2.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/system_v_proc_ss_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_v_proc_ss_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
